### ISSUE TITLE
origin should be equal to target remote

### ISSUE THREAD

**Issue by sbidoul** [acsone/git-aggregator#1]
When using `pip install -e` then `pip freeze`, it seems pip uses the origin remote in the frozen requirements.

So it seems it would be better to have `origin` point to the target remote after the aggregation.

**Comment by lmignon** [comment]
you can achieve the expected result by using the `origin` prefix for your branch where to push the result of the aggregation. 
```yaml
./product_attribute:
    remotes:
        oca: https://github.com/OCA/product-attribute.git
        origin: git+ssh://git@github.com/acsone/product-attribute.git
    merges:
        - oca 8.0
        - oca refs/pull/105/head
        - oca refs/pull/106/head
    target: origin aggregated_branch_name
```
