### ISSUE TITLE
what is ``target`` and coud it made to be optional ?

### ISSUE THREAD

**Issue by vaab** [acsone/git-aggregator#30]
In our process, and in the documentation, it was not clear at first what purpose would serve the currently mandatory ``target`` option in yaml config file. After doing some tinkering, it seems to me that it actually should be optional, it could maybe be required only for special occasion (thinking of push functionality)... but even then, it seems it would be better moved away.

As we can see in your documentation example, it seems both part of the target the "remote" or the "branch" part are either not used (the remote is only used on push, which is optional), or could be kept as an internal implementation choice or fixed value as it appears to be the branch name where we will merge all merge targets.

I could understand to keep this as an option, but because of its apparent similarity with the format of remotes, which are actually not at all the same, this generates much mis-comprehension. For instance the reference part of ``target`` can only be a branch name (whereas reference part of ``merge`` supports commits sha1 and tags)... and target's branch anyway will be created (or ``reset``ed if existent in the repository) anyway.

For me, to the best of my imperfect knowledge, it seems an improvement to remove this option whenever we don't need it. 

It seems it could be called "push-target", and be optional.

What are your thoughts ?

**Comment by sbidoul** [comment]
I think `target` must stay as a required option, as it is first and formost the name of the local branch where merges are aggregated. Also I think it's best keeping compatibility if we change anything.

Perhaps an improvement to `--help` text would suffice?

**Comment by yelizariev** [comment]
``target`` may be required, but I'd prefer to have ``remote_name`` optional. Otherwise, it's confusing, when pushing is not needed. For example in doodba. 
```
# Odoo must be in the `odoo` folder for Doodba to work
odoo:
  defaults:
    # This will use git shallow clones.
    # $DEPTH_DEFAULT is 1 in test and prod, but 100 in devel.
    # $DEPTH_MERGE is always 100.
    # You can use any integer value, OTOH.
    depth: $DEPTH_MERGE
  remotes:
    origin: https://github.com/OCA/OCB.git
    odoo: https://github.com/odoo/odoo.git
    openupgrade: https://github.com/OCA/OpenUpgrade.git
  # $ODOO_VERSION is... the Odoo version! "11.0" or similar
  target: origin $ODOO_VERSION
  merges:
    - origin $ODOO_VERSION
    - odoo refs/pull/25594/head # Expose `Field` from search_filters.js

```
We can set any value in ``target`` instead of ``origin`` and it will not change anything
