### ISSUE TITLE
Semantic problem

### ISSUE THREAD

**Issue by blaggacao** [acsone/git-aggregator#42]
```yaml
...
merges:
  - depth:  # problem
```

I understand the depth is principally on the remote, imagine the case where you merge different refs from the same remote. What happens if `depth=1`?
