### ISSUE TITLE
Proposal: rebase on primary upstream

### ISSUE THREAD

**Issue by blaggacao** [acsone/git-aggregator#43]
An optomized workflow would be in my opinion represented as follows:

```yaml
...
origin: <url>
upstream: 
  url: <url>
  ref: <ref>
  rebase: <default: true>  # target will be rebased on upstream, first
remotes:
  - name: <name>
    url: <url>
    merge:
       - <ref>
       - <ref>
target: <branchname on local & origin>
...
```
