### ISSUE TITLE
Not possible to get specific commit

### ISSUE THREAD

**Issue by thomaspaulb** [acsone/git-aggregator#50]
I'm using latest gitaggregator 1.8.1.

I'm running `gitaggregate --expand-env --config repos.yaml --jobs 4 aggregate`

I have this in my config file:

```
ICTSTUDIO/odoo-extra-addons:
  defaults:
    depth: 100
  remotes:
    origin: https://github.com/ICTSTUDIO/odoo-extra-addons.git
  target: origin 10.0
  merges:
    - origin 6105fb108c2fa27fee68bab7a5fb9af95e4166e
  fetch_all: true
```

I'm getting:

Traceback (most recent call last):
  File "/data/buildout/freshfilter/.venv/lib/python2.7/site-packages/git_aggregator/main.py", line 219, in aggregate_repo
    repo.aggregate()
  File "/data/buildout/freshfilter/.venv/lib/python2.7/site-packages/git_aggregator/repo.py", line 191, in aggregate
    self._merge(merge)
  File "/data/buildout/freshfilter/.venv/lib/python2.7/site-packages/git_aggregator/repo.py", line 270, in _merge
    self.log_call(cmd, cwd=self.cwd)
  File "/data/buildout/freshfilter/.venv/lib/python2.7/site-packages/git_aggregator/repo.py", line 160, in log_call
    ret = callwith(cmd, **kw)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '(u'git', u'pull', u'--no-edit', u'--quiet', u'--depth', '100', 'origin', '6105fb108c2fa27fee68bab7a5fb9af95e4166e')' returned non-zero exit status 1

**Comment by sbidoul** [comment]
If you want to apply a single commit, you can use something like this
```
shell_command_after:
  - curl -sSL https://github.com/ICTSTUDIO/odoo-extra-addons/commit/6105fb108c2fa27fee68bab7a5fb9af95e4166e.patch | git am
```

**Comment by thomaspaulb** [comment]
I think what I meant to do here was not to cherry-pick a single commit, but to checkout the branch at a certain commit (branch pinning). However I think it is implemented by [this patch](https://github.com/acsone/git-aggregator/pull/29/files) I just have to change

```
  merges:
    - origin 6105fb108c2fa27fee68bab7a5fb9af95e4166e
```

to 

```
  merges:
    - origin 10.0 6105fb108c2fa27fee68bab7a5fb9af95e4166e
```

So this can be closed.

**Comment by janverb** [comment]
I don't think that patch enables that as-is, I wrote c5bbedf87c65e5cf5602dc145b32e1aaa13de4de on top of it to support that.

**Comment by thomaspaulb** [comment]
@janverb Is that in a PR at the moment?

**Comment by janverb** [comment]
Not yet. I'd have to add some documentation to make it PR-ready, and it would be nice to have #29 merged first.

**Comment by sbidoul** [comment]
Can you check if this works better with the last release, which changed the strategy to clone+fetch.

**Comment by thomaspaulb** [comment]
> Can you check if this works better with the last release, which changed the strategy to clone+fetch.

I've checked, and yes, this particular example now works better with the clone+fetch strategy.

I've also checked a more complicated example with several sources:

```
OCA/web:
  defaults:
    depth: 10
  remotes:
    origin: https://github.com/OCA/web.git
    forgeflow: https://github.com/forgeflow/web.git
  target: origin 10.0
  merges:
    - origin d20edd1b171c166b6f7d016ac2cfb044a95f084f
    - forgeflow 27be86ab189d91aeb9b4be7bb11198dc016f43fa
```

Which works, so this can be closed.
