### ISSUE TITLE
Question: using with GitLab and Bitbucket

### ISSUE THREAD

**Issue by ivs-cetmix** [acsone/git-aggregator#87]
First of all thank you for the great tool!

There is an example for Gihub:

```
./product_attribute:
    remotes:
        oca: https://github.com/OCA/product-attribute.git
        acsone: git+ssh://git@github.com/acsone/product-attribute.git
    merges:
        - oca 8.0
        - oca refs/pull/105/head
        - oca refs/pull/106/head
```

Is there something similar for GitLab and Bitbucket merge requests?
